[package]
name = "idx"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "idx"
path = "src/main.rs"

[dependencies]
crossbeam = "0.8.4"
num-traits = "0.2.19"
tokio = { version = "1.40.0", features = ["fs", "io-util", "macros", "rt", "rt-multi-thread", "sync", "test-util"] }
